# Generated by Django 4.0.4 on 2022-05-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
